void exit(int code);
asm "@exit"
asm "ldr r0,[sp]"
asm "mov r7,#248"
asm "swi 0"
int open(char *name,int flags,int mode);
asm "@open"
asm "ldm sp,{r0,r1,r2}"
asm "stmdb sp!,{r7,r12}"
asm "mov r7,#5"
asm "swi 0"
asm "ldmia sp!,{r7,r12}"
asm "bx lr"
int read(int fd,void *buf,unsigned int size);
asm "@read"
asm "ldm sp,{r0,r1,r2}"
asm "stmdb sp!,{r7,r12}"
asm "mov r7,#3"
asm "swi 0"
asm "ldmia sp!,{r7,r12}"
asm "bx lr"
int write(int fd,void *buf,unsigned int size);
asm "@write"
asm "ldm sp,{r0,r1,r2}"
asm "stmdb sp!,{r7,r12}"
asm "mov r7,#4"
asm "swi 0"
asm "ldmia sp!,{r7,r12}"
asm "bx lr"
int openat(int dirfd,char *name,int flags,int mode);
asm "@openat"
asm "ldm sp,{r0,r1,r2,r3}"
asm "stmdb sp!,{r7,r12}"
asm "movw r7,#322"
asm "swi 0"
asm "ldmia sp!,{r7,r12}"
asm "bx lr"
int close(int fd);
asm "@close"
asm "ldr r0,[sp]"
asm "stmdb sp!,{r7,r12}"
asm "mov r7,#6"
asm "swi 0"
asm "ldmia sp!,{r7,r12}"
asm "bx lr"
void *brk(void *addr);
asm "@brk"
asm "ldr r0,[sp]"
asm "stmdb sp!,{r7,r12}"
asm "mov r7,#45"
asm "swi 0"
asm "ldmia sp!,{r7,r12}"
asm "bx lr"
